serve_my_kind_network: "{{ serve_my_kind_cluster_name }}-net"
serve_my_kind_network_cidr: "172.30.0.0/16"

serve_my_kind_system_namespace: "{{ serve_my_kind_cluster_name }}-system"
serve_my_kind_configure_dns: true
