serve_my_kind_cluster_name: "kind-local"

serve_my_kind_kubeconfig_path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.kube/config"

serve_my_kind_networking_namespace: "kube-networking"
serve_my_kind_certification_namespace: "kube-certs"

serve_my_kind_certificate_days_validity: 365

serve_my_kind_default_ingress_class: "nginx"

serve_my_kind_hubble_enabled: true
serve_my_kind_hubble_relay_enabled: true
serve_my_kind_hubble_ui_enabled: true
serve_my_kind_hubble_metrics_enabled:
  - "dns"
  - "drop"
  - "tcp"
  - "flow"
  - "icmp"
  - "http"

serve_my_kind_purge_failed_deployments: true
