---
- name: "Add NGINX Ingress Controller Helm Chart Repository if not available"
  ansible.builtin.command: "helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx"

- name: "Install Ingress NGINX Controller via Helm Chart"
  kubernetes.core.helm:
    name: "ingress-nginx"
    chart_ref: "ingress-nginx/ingress-nginx"
    release_namespace: "{{ serve_my_kind_networking_namespace }}"
    state: "present"
    kubeconfig: "{{ serve_my_kind_kubeconfig_path }}"
    wait: true
    wait_timeout: "{{ _serve_my_kind_cni_ingress_creation_timeout }}"
    values:
      defaultBackend:
        enabled: true
      fullnameOverride: "{{ serve_my_kind_cluster_name }}-ingress"
      controller:
        service:
          externalTrafficPolicy: Local
          type: LoadBalancer
      ingressClassResource:
        name: "{{ serve_my_kind_ingress_type }}"
        default: true
