---
- name: "Create DNS-ready Kind cluster with NGINX Ingress"
  hosts: "all"
  connection: "local"
  any_errors_fatal: true
  become: true
  tasks:
    - block:
      - ansible.builtin.include_role: { name: "utils", tasks_from: "install" }
      - ansible.builtin.include_role: { name: "cluster", tasks_from: "create" }
      - ansible.builtin.include_role: { name: "cni", tasks_from: "setup" }
      - ansible.builtin.include_role: { name: "bridge", tasks_from: "create" }
      - ansible.builtin.include_role: { name: "dns", tasks_from: "configure" }
      rescue:
        - name: "Remove failed Kind Cluster deployment"
          ansible.builtin.command: "kind delete clusters {{ serve_my_kind_cluster_name }}"
          ignore_errors: true
        - meta: end_play
