---
- name: "Create DNS-ready Kind cluster with NGINX Ingress"
  hosts: "all"
  connection: "local"
  any_errors_fatal: true
  become: true
  tasks:
    - name: "Set cluster domain"
      set_fact:
        serve_my_kind_cluster_domain: "{{ serve_my_kind_cluster_name | replace('-', '.') }}"
    - block:
      - ansible.builtin.include_role: { name: "utils", tasks_from: "install" }
      - ansible.builtin.include_role: { name: "cluster", tasks_from: "create" }
      - ansible.builtin.include_role: { name: "cni", tasks_from: "setup" }
      - ansible.builtin.include_role: { name: "ca", tasks_from: "establish" }
      - ansible.builtin.include_role: { name: "dns", tasks_from: "configure" }
      - ansible.builtin.include_role: { name: "post", tasks_from: "endpoints" }
      - ansible.builtin.include_role: { name: "ca", tasks_from: "trust" }
