---
- name: "Remove Kind cluster"
  hosts: "all"
  connection: "local"
  any_errors_fatal: true
  become: true
  tasks:
    - ansible.builtin.include_role: { name: "bridge", tasks_from: "disconnect" }
    - ansible.builtin.include_role: { name: "dns", tasks_from: "revert" }
    - ansible.builtin.include_role: { name: "cluster", tasks_from: "remove" }
