---
- name: "Check if dnsmasq is installed"
  ansible.builtin.command: "dnsmasq --version"
  register: dnsmasq_version_check
  ignore_errors: true

- name: "Install dnsmasq"
  ansible.builtin.package:
    name: "dnsmasq"
    state: "present"
  when: "dnsmasq_version_check.rc != 0"

- name: "Check if NetworkManager dnsmasq configuration directory exists"
  ansible.builtin.stat:
    path: "/etc/NetworkManager/dnsmasq.d"
  register: "dnsmasq_conf_dir_check"

- name: "Create dnsmasq configuration directory"
  ansible.builtin.file:
    path: "/etc/NetworkManager/dnsmasq.d"
    state: "directory"
  when: "not dnsmasq_conf_dir_check.stat.exists"
