- name: "Check if cert-manager Helm repo is added"
  kubernetes.core.helm_repository:
    name: "jetstack"
    state: "present"
    repo_url: "https://charts.jetstack.io"
  register: "serve_my_kind_setup_cluster_certmanager_repo_check"

- name: "Add cert-manager Helm repo if not available"
  kubernetes.core.helm_repository:
    name: "jetstack"
    state: "present"
    repo_url: "https://charts.jetstack.io"
  when: "serve_my_kind_setup_cluster_certmanager_repo_check is failed"

- name: "Install the cert-manager Helm Chart"
  kubernetes.core.helm:
    name: "cert-manager"
    chart_ref: "jetstack/cert-manager"
    release_namespace: "{{ serve_my_kind_system_namespace }}"
    state: "present"
    kubeconfig: "{{ serve_my_kind_kubeconfig_path }}"
    values:
      installCRDs:
        true

- name: "Render the manifest for issuers"
  ansible.builtin.template:
    src: "cert-issuers.yml.j2"
    dest: "{{ serve_my_kind_manifests_and_configs_path }}/cert-issuers.yml"

- name: "Create the ClusterIssuers"
  kubernetes.core.k8s:
    state: "present"
    src: "{{ serve_my_kind_manifests_and_configs_path }}/cert-issuers.yml"
    kubeconfig: "{{ serve_my_kind_kubeconfig_path }}"

- name: "Store the ClusterIssuers names in ConfigMap within {{ serve_my_kind_system_namespace }}"
  kubernetes.core.k8s:
    state: "present"
    definition:
      apiVersion: "v1"
      kind: "ConfigMap"
      metadata:
        name: "{{ serve_my_kind_setup_clister_issuers_names_configmap_name }}"
        namespace: "{{ serve_my_kind_system_namespace }}"
      data:
        staging: "{{ serve_my_kind_setup_cluster_staging_issuer_name }}"
        production: "{{ serve_my_kind_setup_cluster_production_issuer_name }}"
        selfSigned: "{{ serve_my_kind_setup_cluster_self_signed_issuer_name }}"
    kubeconfig: "{{ serve_my_kind_kubeconfig_path }}"
    validate: "no"
    force: "yes"
