- name: "Check if Cilium Helm repo is added"
  kubernetes.core.helm_repository:
    name: "cilium"
    state: "present"
    repo_url: "https://helm.cilium.io/"
  register: "serve_my_kind_setup_cluster_cilium_repo_check"

- name: "Add Cilium Helm repo if not available"
  kubernetes.core.helm_repository:
    name: "cilium"
    state: "present"
    repo_url: "https://helm.cilium.io/"
  when: "serve_my_kind_setup_cluster_cilium_repo_check is failed"

- name: "Render Cilium Helm values file"
  ansible.builtin.template:
    src: "cilium.yml.j2"
    dest: "{{ serve_my_kind_manifests_and_configs_path }}/cilium.yml"

- name: "Install Cilium Helm Chart with values file"
  kubernetes.core.helm:
    name: "cilium"
    chart_ref: "cilium/cilium"
    release_namespace: "{{ serve_my_kind_system_namespace }}"
    create_namespace: true
    state: "present"
    kubeconfig: "{{ serve_my_kind_kubeconfig_path }}"
    values_files:
      - "{{ serve_my_kind_manifests_and_configs_path }}/cilium.yml"

- name: "Wait for Cilium LoadBalancer IP Pool CRD to be available"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ serve_my_kind_kubeconfig_path }}"
    kind: CustomResourceDefinition
    api_version: "apiextensions.k8s.io/v1"
    name: ciliumloadbalancerippools.cilium.io
  register: "serve_my_kind_setup_cluster_cilium_loadbalancerippool_crd_check"
  until: "serve_my_kind_setup_cluster_cilium_loadbalancerippool_crd_check.resources | length > 0"

- name: "Get Kind network CIDR via inspecting the {{ serve_my_kind_network }} network"
  command: "docker network inspect {{ serve_my_kind_network }}"
  register: "serve_my_kind_setup_cluster_kind_network_info"
  changed_when: false

- name: "Create Cilium IPPool manifest"
  kubernetes.core.k8s:
    kubeconfig: "{{ serve_my_kind_kubeconfig_path }}"
    definition:
      apiVersion: "cilium.io/v2alpha1"
      kind: CiliumLoadBalancerIPPool
      metadata:
        name: "pool"
      spec:
        cidrs:
        - cidr: "{{ serve_my_kind_setup_cluster_kind_network_info.stdout | from_json | json_query('[].IPAM.Config[?Subnet].Subnet') | first }}"
