---
- name: "Setup Cluster"
  block:
    - name: "Check if Docker network exists"
      ansible.builtin.command: "docker network inspect {{ serve_my_kind_network }}"
      register: serve_my_kind_configure_dns_docker_network_check
      ignore_errors: true

    - name: "Prepare Docker network for cluster"
      ansible.builtin.include_tasks: "network.yml"
      when: "serve_my_kind_configure_dns_docker_network_check.rc != 0"

    - name: "Check if Kind Cluster is already created"
      ansible.builtin.command: "kind get clusters"
      register: serve_my_kind_current_clusters_list
      changed_when: false
      failed_when: false

    - name: "Create Kind cluster"
      ansible.builtin.include_tasks: "cluster.yml"
      when: serve_my_kind_current_clusters_list.stdout.find(serve_my_kind_cluster_name) == -1

    - name: "Install Cilium"
      ansible.builtin.include_tasks: "cilium.yml"
    
    - name: "Install NGINX Ingress Controller"
      ansible.builtin.include_tasks: "ingress-nginx.yml"
      when: serve_my_kind_ingress_type == "ingress-nginx"
  rescue:
    - name: "Remove failed Kind Cluster deployment"
      ansible.builtin.command: "kind delete clusters {{ serve_my_kind_cluster_name }}"
      ignore_errors: true
    - meta: end_play
