---
- name: "Check if Docker network exists"
  ansible.builtin.command: "docker network inspect {{ fastkind_network }}"
  register: fastkind_configure_dns_docker_network_check
  ignore_errors: true

- name: "Prepare Docker network for cluster"
  ansible.builtin.include_tasks: "network.yml"
  when: "fastkind_configure_dns_docker_network_check.rc != 0"

- name: "Check if Kind Cluster is already created"
  ansible.builtin.command: "kind get clusters"
  register: fastkind_current_clusters_list
  changed_when: false
  failed_when: false

- name: "Create Kind cluster"
  ansible.builtin.include_tasks: "cluster.yml"
  when: fastkind_current_clusters_list.stdout.find(fastkind_cluster_name) == -1

- name: "Install NGINX Ingress Controller"
  ansible.builtin.include_tasks: "install-ingress-nginx.yml"
  when: fastkind_ingress_type == "ingress-nginx"
