_fastkind_ensure_tools_kind_version: "v0.20.0"
_fastkind_ensure_tools_kubectl_version: "v1.30.0"
_fastkind_ensure_tools_kubeadmin_version: "v1.30.0"

_fastkind_ensure_tools_arm64_urls:
  kind: "https://kind.sigs.k8s.io/dl/{{ _fastkind_ensure_tools_kind_version }}/kind-linux-arm64"
  kubectl: "https://dl.k8s.io/release/{{ _fastkind_ensure_tools_kubectl_version }}/bin/linux/arm64/kubectl"

_fastkind_ensure_tools_x86_64_urls:
  kind: "https://kind.sigs.k8s.io/dl/{{ _fastkind_ensure_tools_kind_version }}/kind-linux-amd64"
  kubectl: "https://dl.k8s.io/release/{{ _fastkind_ensure_tools_kubectl_version }}/bin/linux/amd64/kubectl"
