- name: "Generate the self-signed certificate using OpenSSL"
  ansible.builtin.include_tasks: "certificate.yml"

- name: "Create a secret containing the self-signed certificate for the bridge"
  ansible.builtin.command:
    cmd: >
      kubectl create secret tls "{{ _serve_my_kind_bridge_self_signed_ca_secret_name }}"
      --kubeconfig="{{ serve_my_kind_kubeconfig_path }}"
      --namespace="{{ serve_my_kind_networking_namespace }}"
      --cert="{{ _serve_my_kind_bridge_self_signed_ca_cert_file }}"
      --key="{{ _serve_my_kind_bridge_self_signed_ca_key_file }}"

- name: "Render the manifest for issuers"
  ansible.builtin.template:
    src: "cert-issuers.yml.j2"
    dest: "{{ serve_my_kind_manifests_and_configs_path }}/cert-issuers.yml"

- name: "Create the ClusterIssuers"
  kubernetes.core.k8s:
    state: "present"
    src: "{{ serve_my_kind_manifests_and_configs_path }}/cert-issuers.yml"
    kubeconfig: "{{ serve_my_kind_kubeconfig_path }}"
    wait: true
    wait_timeout: "{{ _serve_my_kind_bridge_issuers_creation_timeout }}"
