- name: "Setup certification for the bridging between host and cluster"
  block:
    - name: "Install Cert-Manager"
      ansible.builtin.include_tasks: "cert-manager.yml"

    - name: "Create Kind cluster certificate issuers"
      ansible.builtin.include_tasks: "cert-issuers.yml"
  rescue:
    - name: Clean up generated CA files if failed
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ _serve_my_kind_bridge_self_signed_ca_key_file }}"
        - "{{ _serve_my_kind_bridge_self_signed_ca_cert_file }}"
    - ansible.builtin.fail:
        msg: "Failed to setup certification for the bridging between host and cluster"
