- name: "Remove Kind Cluster"
  ansible.builtin.command: "kind delete clusters --kubeconfig={{ serve_my_kind_kubeconfig_path }} {{ serve_my_kind_cluster_name }}"

- name: "Remove Docker network"
  ansible.builtin.shell: "docker network rm {{ serve_my_kind_network }}"
  ignore_errors: true

- name: "Remove cluster SSL certificates from trusted ones on host"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  loop:
    - "/usr/local/share/ca-certificates/{{ serve_my_kind_cluster_name }}-root-ca.crt"
    - "{{ serve_my_kind_host_certificates_dir }}/{{ serve_my_kind_cluster_name }}-root-ca.pem"
    - "{{ serve_my_kind_host_certificates_dir }}/{{ serve_my_kind_cluster_name }}-root-ca.key"

- name: "Reload the trusted SSL certificates"
  ansible.builtin.command: "update-ca-certificates"
