serve_my_kind_cluster_name: "kind-local"

serve_my_kind_setup_cluster_normal_workers: 2
serve_my_kind_setup_cluster_special_nodes: []

serve_my_kind_setup_cluster_cert_manager_enabled: true
serve_my_kind_setup_cluster_production_issuer_name: "{{ serve_my_kind_cluster_name }}-letsencrypt-production"
serve_my_kind_setup_cluster_staging_issuer_name: "{{ serve_my_kind_cluster_name }}-letsencrypt-staging"
serve_my_kind_setup_cluster_self_signed_issuer_name: "{{ serve_my_kind_cluster_name }}-letsencrypt-self-signed"
serve_my_kind_setup_cluster_issuers_names_configmap_name: "{{ serve_my_kind_cluster_name }}-cert-issuers-names"

serve_my_kind_setup_cluster_hubble_enabled: true
serve_my_kind_setup_cluster_hubble_relay_enabled: true
serve_my_kind_setup_cluster_hubble_ui_enabled: true
serve_my_kind_setup_clister_hubble_metrics_enabled:
  - "dns"
  - "drop"
  - "tcp"
  - "flow"
  - "icmp"
  - "http"

serve_my_kind_setup_cluster_enable_strict_arp: false
serve_my_kind_setup_cluster_load_balancer_l2_advertisement_name: "{{ serve_my_kind_cluster_name }}-l2-advertisement"
serve_my_kind_setup_cluster_load_balancer_address_pool_name: "{{ serve_my_kind_cluster_name }}-default-pool"
