- name: "Add ACME provisioner for {{ _serve_my_kind_issuer_type }} ClusterIssuer"
  community.docker.docker_container_exec:
    container: "{{ serve_my_kind_cluster_name }}-step-ca"
    command: "step ca provisioner add {{ serve_my_kind_cluster_name }}-{{ _serve_my_kind_issuer_type }} --type ACME"
    env:
      STEPPATH: "/home/step"

- name: "Render the manifest for issuer"
  ansible.builtin.template:
    src: "acme-issuer.yml.j2"
    dest: "{{ serve_my_kind_manifests_and_configs_path }}/{{ _serve_my_kind_issuer_type }}-issuer.yml"

- name: "Create the {{ _serve_my_kind_certification_issuer_name }} ClusterIssuer"
  kubernetes.core.k8s:
    state: "present"
    src: "{{ serve_my_kind_manifests_and_configs_path }}/{{ _serve_my_kind_issuer_type }}-issuer.yml"
    kubeconfig: "{{ serve_my_kind_kubeconfig_path }}"
    wait: true
    wait_timeout: "{{ _serve_my_kind_certification_issuers_creation_timeout }}"
