- name: "Generate a new self-signed certificate for the cluster"
  ansible.builtin.command: "openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout {{ serve_my_kind_host_certificates_dir }}/{{ _serve_my_kind_certification_domain_ca_secret_name }}.key -out {{ serve_my_kind_host_certificates_dir }}/{{ _serve_my_kind_certification_domain_ca_secret_name }}.pem -subj '/CN={{ serve_my_kind_cluster_name }}-root-ca'"

- name: "Create a Secret in {{ serve_my_kind_certification_namespace }} with the root CA certificate"
  kubernetes.core.k8s:
    state: "present"
    definition:
      apiVersion: "v1"
      kind: "Secret"
      metadata:
        name: "{{ _serve_my_kind_certification_domain_ca_secret_name }}"
        namespace: "{{ serve_my_kind_certification_namespace }}"
      data:
        tls.crt: "{{ lookup('file', '{{ serve_my_kind_host_certificates_dir }}/{{ _serve_my_kind_certification_domain_ca_secret_name }}.pem') }}"
        tls.key: "{{ lookup('file', '{{ serve_my_kind_host_certificates_dir }}/{{ _serve_my_kind_certification_domain_ca_secret_name }}.key') }}"
    kubeconfig: "{{ serve_my_kind_kubeconfig_path }}"
    wait: true

- name: "Render cluster issuers"
  ansible.builtin.template:
    src: "cluster-issuers.yml.j2"
    dest: "{{ serve_my_kind_manifests_and_configs_path }}/cluster-issuers.yml"

- name: "Create cluster issuers"
  kubernetes.core.k8s:
    state: "present"
    src: "{{ serve_my_kind_manifests_and_configs_path }}/cluster-issuers.yml"
    kubeconfig: "{{ serve_my_kind_kubeconfig_path }}"
    wait: true

- name: "Find the name of Ingress Nginx Controller Deployment"
  ansible.builtin.command: "kubectl --kubeconfig={{ serve_my_kind_kubeconfig_path }} get deployment -n {{ serve_my_kind_networking_namespace }} -l app.kubernetes.io/name=ingress-nginx -o jsonpath='{.items[0].metadata.name}'"
  register: _serve_my_kind_certification_nginx_ingress_controller_name

- name: "Add the argument to the Ingress Nginx Controller Deployment"
  ansible.builtin.command: >
    kubectl --kubeconfig={{ serve_my_kind_kubeconfig_path }} patch deployment {{ _serve_my_kind_certification_nginx_ingress_controller_name.stdout }}
    -n {{ serve_my_kind_networking_namespace }}
    --type='json'
    -p='[{"op": "add", "path": "/spec/template/spec/containers/0/args/-", "value": "--default-ssl-certificate={{ serve_my_kind_certification_namespace }}/{{ _serve_my_kind_certification_domain_ca_secret_name }}"}]'
