- name: "Check if cert-manager Helm repo is added"
  kubernetes.core.helm_repository:
    name: "jetstack"
    state: "present"
    repo_url: "https://charts.jetstack.io"
  register: "serve_my_kind_ingress_certmanager_repo_check"

- name: "Add cert-manager Helm repo if not available"
  kubernetes.core.helm_repository:
    name: "jetstack"
    state: "present"
    repo_url: "https://charts.jetstack.io"
  when: "serve_my_kind_ingress_certmanager_repo_check is failed"

- name: "Install the cert-manager Helm Chart"
  kubernetes.core.helm:
    name: "cert-manager"
    chart_ref: "jetstack/cert-manager"
    release_namespace: "{{ serve_my_kind_networking_namespace }}"
    state: "present"
    kubeconfig: "{{ serve_my_kind_kubeconfig_path }}"
    values:
      installCRDs:
        true
    wait: true
