- name: "Remove cluster SSL certificates from trusted ones on host"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  loop:
    - "/usr/local/share/ca-certificates/{{ serve_my_kind_cluster_name }}-root-ca.crt"
    - "{{ serve_my_kind_host_certificates_dir }}/{{ serve_my_kind_cluster_name }}-root-ca.pem"

- name: "Reload the trusted SSL certificates"
  ansible.builtin.command: "update-ca-certificates"
