serve_my_kind_cluster_name: "cluster-local"
serve_my_kind_kubeconfig_path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.kube/config"
serve_my_kind_manifests_and_configs_path: "/tmp"

serve_my_kind_networking_namespace: "kube-networking"
serve_my_kind_network: "{{ serve_my_kind_cluster_name }}-net"
serve_my_kind_network_cidr: "172.30.0.0/16"
serve_my_kind_default_ingress_class: "nginx"
serve_my_kind_configure_dns: true

serve_my_kind_certification_namespace: "kube-certs"
serve_my_kind_host_certificates_dir: "/etc/ssl/certs"
serve_my_kind_ca_issuer_name: "{{ serve_my_kind_cluster_name }}-ca"
serve_my_kind_certificate_days_validity: 365

serve_my_kind_hubble_enabled: true
serve_my_kind_hubble_relay_enabled: true
serve_my_kind_hubble_ui_enabled: true
serve_my_kind_hubble_metrics_enabled:
  - "dns"
  - "drop"
  - "tcp"
  - "flow"
  - "icmp"
  - "http"
